import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Gujarat cities with translations - including major cities, towns, and villages
export const GUJARAT_CITIES: Record<Language, Record<string, string>> = {
  en: {
    // Major Cities
    'Ahmedabad': 'Ahmedabad',
    'Surat': 'Surat',
    'Vadodara': 'Vadodara',
    'Rajkot': 'Rajkot',
    'Bhavnagar': 'Bhavnagar',
    'Jamnagar': 'Jamnagar',
    'Junagadh': 'Junagadh',
    'Gandhinagar': 'Gandhinagar',
    'Anand': 'Anand',
    'Nadiad': 'Nadiad',
    'Morbi': 'Morbi',
    'Mehsana': 'Mehsana',
    'Bharuch': 'Bharuch',
    'Vapi': 'Vapi',
    'Navsari': 'Navsari',
    'Veraval': 'Veraval',
    'Porbandar': 'Porbandar',
    'Godhra': 'Godhra',
    'Bhuj': 'Bhuj',
    'Palanpur': 'Palanpur',
    'Valsad': 'Valsad',
    'Patan': 'Patan',
    'Dahod': 'Dahod',
    'Amreli': 'Amreli',
    'Surendranagar': 'Surendranagar',
    'Kutch': 'Kutch',
    'Dwarka': 'Dwarka',
    'Somnath': 'Somnath',
    'Kheda': 'Kheda',
    'Sabarkantha': 'Sabarkantha',
    // Smaller Towns & Villages
    'Gandhidham': 'Gandhidham',
    'Bardoli': 'Bardoli',
    'Jetpur': 'Jetpur',
    'Gondal': 'Gondal',
    'Botad': 'Botad',
    'Visnagar': 'Visnagar',
    'Kalol': 'Kalol',
    'Modasa': 'Modasa',
    'Himmatnagar': 'Himmatnagar',
    'Idar': 'Idar',
    'Khedbrahma': 'Khedbrahma',
    'Vijapur': 'Vijapur',
    'Kadi': 'Kadi',
    'Unjha': 'Unjha',
    'Deesa': 'Deesa',
    'Dhanera': 'Dhanera',
    'Radhanpur': 'Radhanpur',
    'Sidhpur': 'Sidhpur',
    'Vadnagar': 'Vadnagar',
    'Chanasma': 'Chanasma',
    'Harij': 'Harij',
    'Petlad': 'Petlad',
    'Khambhat': 'Khambhat',
    'Borsad': 'Borsad',
    'Umreth': 'Umreth',
    'Tarapur': 'Tarapur',
    'Sojitra': 'Sojitra',
    'Dakor': 'Dakor',
    'Kapadvanj': 'Kapadvanj',
    'Thasra': 'Thasra',
    'Mahemdabad': 'Mahemdabad',
    'Halol': 'Halol',
    'Lunawada': 'Lunawada',
    'Santrampur': 'Santrampur',
    'Devgadh Baria': 'Devgadh Baria',
    'Limkheda': 'Limkheda',
    'Jhalod': 'Jhalod',
    'Fatepura': 'Fatepura',
    'Dholka': 'Dholka',
    'Sanand': 'Sanand',
    'Bavla': 'Bavla',
    'Mandal': 'Mandal',
    'Viramgam': 'Viramgam',
    'Dhandhuka': 'Dhandhuka',
    'Ranpur': 'Ranpur',
    'Olpad': 'Olpad',
    'Kamrej': 'Kamrej',
    'Palsana': 'Palsana',
    'Mangrol': 'Mangrol',
    'Mahuva': 'Mahuva',
    'Talaja': 'Talaja',
    'Palitana': 'Palitana',
    'Sihor': 'Sihor',
    'Ghogha': 'Ghogha',
    'Gariadhar': 'Gariadhar',
    'Dhari': 'Dhari',
    'Savarkundla': 'Savarkundla',
    'Lathi': 'Lathi',
    'Babra': 'Babra',
    'Khambha': 'Khambha',
    'Rajula': 'Rajula',
    'Jafrabad': 'Jafrabad',
    'Una': 'Una',
    'Kodinar': 'Kodinar',
    'Sutrapada': 'Sutrapada',
    'Mendarda': 'Mendarda',
    'Keshod': 'Keshod',
    'Malia Hatina': 'Malia Hatina',
    'Visavadar': 'Visavadar',
    'Vanthali': 'Vanthali',
    'Bhesan': 'Bhesan',
    'Manavadar': 'Manavadar',
    'Kutiyana': 'Kutiyana',
    'Ranavav': 'Ranavav',
    'Dhoraji': 'Dhoraji',
    'Upleta': 'Upleta',
    'Wankaner': 'Wankaner',
    'Tankara': 'Tankara',
    'Dhrol': 'Dhrol',
    'Jodiya': 'Jodiya',
    'Khambhalia': 'Khambhalia',
    'Lalpur': 'Lalpur',
    'Bhanvad': 'Bhanvad',
    'Kalyanpur': 'Kalyanpur',
    'Okha': 'Okha',
    'Mundra': 'Mundra',
    'Anjar': 'Anjar',
    'Adipur': 'Adipur',
    'Nakhatrana': 'Nakhatrana',
    'Bhachau': 'Bhachau',
    'Rapar': 'Rapar',
    'Abdasa': 'Abdasa',
    'Lakhpat': 'Lakhpat',
    'Ahwa': 'Ahwa',
    'Chikhli': 'Chikhli',
    'Bilimora': 'Bilimora',
    'Gandevi': 'Gandevi',
    'Vyara': 'Vyara',
    'Songadh': 'Songadh',
    'Nizar': 'Nizar',
    'Ukai': 'Ukai',
    'Amod': 'Amod',
    'Ankleshwar': 'Ankleshwar',
    'Jhagadia': 'Jhagadia',
    'Jambusar': 'Jambusar',
    'Vagra': 'Vagra',
    'Netrang': 'Netrang',
    'Dediapada': 'Dediapada',
    'Sagbara': 'Sagbara',
    'Nandod': 'Nandod',
    'Rajpipla': 'Rajpipla',
    'Chotila': 'Chotila',
    'Limbdi': 'Limbdi',
    'Halvad': 'Halvad',
    'Dhrangadhra': 'Dhrangadhra',
    'Dasada': 'Dasada',
    'Lakhtar': 'Lakhtar',
    'Muli': 'Muli',
    'Sayla': 'Sayla',
    'Wadhwan': 'Wadhwan',
    'Thangadh': 'Thangadh',
  },
  hi: {
    // Major Cities
    'Ahmedabad': 'अहमदाबाद',
    'Surat': 'सूरत',
    'Vadodara': 'वडोदरा',
    'Rajkot': 'राजकोट',
    'Bhavnagar': 'भावनगर',
    'Jamnagar': 'जामनगर',
    'Junagadh': 'जूनागढ़',
    'Gandhinagar': 'गांधीनगर',
    'Anand': 'आनंद',
    'Nadiad': 'नडियाद',
    'Morbi': 'मोरबी',
    'Mehsana': 'मेहसाणा',
    'Bharuch': 'भरूच',
    'Vapi': 'वापी',
    'Navsari': 'नवसारी',
    'Veraval': 'वेरावल',
    'Porbandar': 'पोरबंदर',
    'Godhra': 'गोधरा',
    'Bhuj': 'भुज',
    'Palanpur': 'पालनपुर',
    'Valsad': 'वलसाड',
    'Patan': 'पाटन',
    'Dahod': 'दाहोद',
    'Amreli': 'अमरेली',
    'Surendranagar': 'सुरेंद्रनगर',
    'Kutch': 'कच्छ',
    'Dwarka': 'द्वारका',
    'Somnath': 'सोमनाथ',
    'Kheda': 'खेड़ा',
    'Sabarkantha': 'साबरकांठा',
    // Smaller Towns & Villages
    'Gandhidham': 'गांधीधाम',
    'Bardoli': 'बारडोली',
    'Jetpur': 'जेतपुर',
    'Gondal': 'गोंडल',
    'Botad': 'बोटाद',
    'Visnagar': 'विसनगर',
    'Kalol': 'कालोल',
    'Modasa': 'मोडासा',
    'Himmatnagar': 'हिम्मतनगर',
    'Idar': 'ईडर',
    'Khedbrahma': 'खेड़ब्रह्मा',
    'Vijapur': 'विजापुर',
    'Kadi': 'कड़ी',
    'Unjha': 'ऊंझा',
    'Deesa': 'डीसा',
    'Dhanera': 'धानेरा',
    'Radhanpur': 'राधनपुर',
    'Sidhpur': 'सिद्धपुर',
    'Vadnagar': 'वडनगर',
    'Chanasma': 'चाणस्मा',
    'Harij': 'हरिज',
    'Petlad': 'पेटलाद',
    'Khambhat': 'खंभात',
    'Borsad': 'बोरसद',
    'Umreth': 'उमरेठ',
    'Tarapur': 'तारापुर',
    'Sojitra': 'सोजित्रा',
    'Dakor': 'डाकोर',
    'Kapadvanj': 'कपडवंज',
    'Thasra': 'थासरा',
    'Mahemdabad': 'महेमदाबाद',
    'Halol': 'हालोल',
    'Lunawada': 'लुनावाड़ा',
    'Santrampur': 'संतरामपुर',
    'Devgadh Baria': 'देवगढ़ बारिया',
    'Limkheda': 'लिमखेड़ा',
    'Jhalod': 'झालोद',
    'Fatepura': 'फतेपुरा',
    'Dholka': 'धोलका',
    'Sanand': 'साणंद',
    'Bavla': 'बावला',
    'Mandal': 'मांडल',
    'Viramgam': 'विरमगाम',
    'Dhandhuka': 'धंधुका',
    'Ranpur': 'रानपुर',
    'Olpad': 'ओलपाड',
    'Kamrej': 'कामरेज',
    'Palsana': 'पालसाना',
    'Mangrol': 'मांगरोल',
    'Mahuva': 'महुवा',
    'Talaja': 'तलाजा',
    'Palitana': 'पालीताणा',
    'Sihor': 'सिहोर',
    'Ghogha': 'घोघा',
    'Gariadhar': 'गढ़डा',
    'Dhari': 'धारी',
    'Savarkundla': 'सावरकुंडला',
    'Lathi': 'लाठी',
    'Babra': 'बाबरा',
    'Khambha': 'खंभा',
    'Rajula': 'राजुला',
    'Jafrabad': 'जाफराबाद',
    'Una': 'ऊना',
    'Kodinar': 'कोडीनार',
    'Sutrapada': 'सुत्रापाड़ा',
    'Mendarda': 'मेंदरडा',
    'Keshod': 'केशोद',
    'Malia Hatina': 'मालिया हाटीना',
    'Visavadar': 'विसावदर',
    'Vanthali': 'वांथली',
    'Bhesan': 'भेसाण',
    'Manavadar': 'मानावदर',
    'Kutiyana': 'कुतियाना',
    'Ranavav': 'रानावाव',
    'Dhoraji': 'धोराजी',
    'Upleta': 'उपलेटा',
    'Wankaner': 'वांकानेर',
    'Tankara': 'टंकारा',
    'Dhrol': 'ढ्रोल',
    'Jodiya': 'जोडिया',
    'Khambhalia': 'खंभालिया',
    'Lalpur': 'लालपुर',
    'Bhanvad': 'भानवड़',
    'Kalyanpur': 'कल्याणपुर',
    'Okha': 'ओखा',
    'Mundra': 'मुंद्रा',
    'Anjar': 'अंजार',
    'Adipur': 'आदीपुर',
    'Nakhatrana': 'नखत्राणा',
    'Bhachau': 'भचाऊ',
    'Rapar': 'रापर',
    'Abdasa': 'अब्दासा',
    'Lakhpat': 'लखपत',
    'Ahwa': 'आहवा',
    'Chikhli': 'चिखली',
    'Bilimora': 'बिलीमोरा',
    'Gandevi': 'गणदेवी',
    'Vyara': 'व्यारा',
    'Songadh': 'सोंगढ़',
    'Nizar': 'निज़र',
    'Ukai': 'उकाई',
    'Amod': 'आमोद',
    'Ankleshwar': 'अंकलेश्वर',
    'Jhagadia': 'झगड़िया',
    'Jambusar': 'जंबूसर',
    'Vagra': 'वागरा',
    'Netrang': 'नेत्रंग',
    'Dediapada': 'डेडियापाड़ा',
    'Sagbara': 'सगबारा',
    'Nandod': 'नांदोद',
    'Rajpipla': 'राजपीपला',
    'Chotila': 'छोटीला',
    'Limbdi': 'लीमड़ी',
    'Halvad': 'हालवाड़',
    'Dhrangadhra': 'ध्रांगध्रा',
    'Dasada': 'दसाड़ा',
    'Lakhtar': 'लखतर',
    'Muli': 'मुली',
    'Sayla': 'सायला',
    'Wadhwan': 'वढवाण',
    'Thangadh': 'थानगढ़',
  },
  gu: {
    // Major Cities
    'Ahmedabad': 'અમદાવાદ',
    'Surat': 'સુરત',
    'Vadodara': 'વડોદરા',
    'Rajkot': 'રાજકોટ',
    'Bhavnagar': 'ભાવનગર',
    'Jamnagar': 'જામનગર',
    'Junagadh': 'જુનાગઢ',
    'Gandhinagar': 'ગાંધીનગર',
    'Anand': 'આણંદ',
    'Nadiad': 'નડિયાદ',
    'Morbi': 'મોરબી',
    'Mehsana': 'મહેસાણા',
    'Bharuch': 'ભરૂચ',
    'Vapi': 'વાપી',
    'Navsari': 'નવસારી',
    'Veraval': 'વેરાવળ',
    'Porbandar': 'પોરબંદર',
    'Godhra': 'ગોધરા',
    'Bhuj': 'ભુજ',
    'Palanpur': 'પાલનપુર',
    'Valsad': 'વલસાડ',
    'Patan': 'પાટણ',
    'Dahod': 'દાહોદ',
    'Amreli': 'અમરેલી',
    'Surendranagar': 'સુરેન્દ્રનગર',
    'Kutch': 'કચ્છ',
    'Dwarka': 'દ્વારકા',
    'Somnath': 'સોમનાથ',
    'Kheda': 'ખેડા',
    'Sabarkantha': 'સાબરકાંઠા',
    // Smaller Towns & Villages
    'Gandhidham': 'ગાંધીધામ',
    'Bardoli': 'બારડોલી',
    'Jetpur': 'જેતપુર',
    'Gondal': 'ગોંડલ',
    'Botad': 'બોટાદ',
    'Visnagar': 'વિસનગર',
    'Kalol': 'કલોલ',
    'Modasa': 'મોડાસા',
    'Himmatnagar': 'હિંમતનગર',
    'Idar': 'ઈડર',
    'Khedbrahma': 'ખેડબ્રહ્મા',
    'Vijapur': 'વિજાપુર',
    'Kadi': 'કડી',
    'Unjha': 'ઊંઝા',
    'Deesa': 'ડીસા',
    'Dhanera': 'ધાનેરા',
    'Radhanpur': 'રાધનપુર',
    'Sidhpur': 'સિદ્ધપુર',
    'Vadnagar': 'વડનગર',
    'Chanasma': 'ચાણસ્મા',
    'Harij': 'હારિજ',
    'Petlad': 'પેટલાદ',
    'Khambhat': 'ખંભાત',
    'Borsad': 'બોરસદ',
    'Umreth': 'ઉમરેઠ',
    'Tarapur': 'તારાપુર',
    'Sojitra': 'સોજિત્રા',
    'Dakor': 'ડાકોર',
    'Kapadvanj': 'કપડવંજ',
    'Thasra': 'ઠાસરા',
    'Mahemdabad': 'મહેમદાબાદ',
    'Halol': 'હાલોલ',
    'Lunawada': 'લુણાવાડા',
    'Santrampur': 'સંતરામપુર',
    'Devgadh Baria': 'દેવગઢ બારિયા',
    'Limkheda': 'લીમખેડા',
    'Jhalod': 'ઝાલોદ',
    'Fatepura': 'ફતેપુરા',
    'Dholka': 'ધોલકા',
    'Sanand': 'સાણંદ',
    'Bavla': 'બાવળા',
    'Mandal': 'માંડલ',
    'Viramgam': 'વીરમગામ',
    'Dhandhuka': 'ધંધુકા',
    'Ranpur': 'રાણપુર',
    'Olpad': 'ઓલપાડ',
    'Kamrej': 'કામરેજ',
    'Palsana': 'પાલસાણા',
    'Mangrol': 'માંગરોળ',
    'Mahuva': 'મહુવા',
    'Talaja': 'તળાજા',
    'Palitana': 'પાલીતાણા',
    'Sihor': 'સિહોર',
    'Ghogha': 'ઘોઘા',
    'Gariadhar': 'ગઢડા',
    'Dhari': 'ધારી',
    'Savarkundla': 'સાવરકુંડલા',
    'Lathi': 'લાઠી',
    'Babra': 'બાબરા',
    'Khambha': 'ખંભા',
    'Rajula': 'રાજુલા',
    'Jafrabad': 'જાફરાબાદ',
    'Una': 'ઊના',
    'Kodinar': 'કોડીનાર',
    'Sutrapada': 'સુત્રાપાડા',
    'Mendarda': 'મેંદરડા',
    'Keshod': 'કેશોદ',
    'Malia Hatina': 'માળિયા હાટીના',
    'Visavadar': 'વિસાવદર',
    'Vanthali': 'વંથલી',
    'Bhesan': 'ભેસાણ',
    'Manavadar': 'માણાવદર',
    'Kutiyana': 'કુતિયાણા',
    'Ranavav': 'રાણાવાવ',
    'Dhoraji': 'ધોરાજી',
    'Upleta': 'ઉપલેટા',
    'Wankaner': 'વાંકાનેર',
    'Tankara': 'ટંકારા',
    'Dhrol': 'ધ્રોલ',
    'Jodiya': 'જોડિયા',
    'Khambhalia': 'ખંભાળિયા',
    'Lalpur': 'લાલપુર',
    'Bhanvad': 'ભાણવડ',
    'Kalyanpur': 'કલ્યાણપુર',
    'Okha': 'ઓખા',
    'Mundra': 'મુંદ્રા',
    'Anjar': 'અંજાર',
    'Adipur': 'આદિપુર',
    'Nakhatrana': 'નખત્રાણા',
    'Bhachau': 'ભચાઉ',
    'Rapar': 'રાપર',
    'Abdasa': 'અબડાસા',
    'Lakhpat': 'લખપત',
    'Ahwa': 'આહવા',
    'Chikhli': 'ચીખલી',
    'Bilimora': 'બીલીમોરા',
    'Gandevi': 'ગણદેવી',
    'Vyara': 'વ્યારા',
    'Songadh': 'સોનગઢ',
    'Nizar': 'નિઝર',
    'Ukai': 'ઉકાઈ',
    'Amod': 'આમોદ',
    'Ankleshwar': 'અંકલેશ્વર',
    'Jhagadia': 'ઝઘડિયા',
    'Jambusar': 'જંબુસર',
    'Vagra': 'વાગરા',
    'Netrang': 'નેત્રંગ',
    'Dediapada': 'ડેડિયાપાડા',
    'Sagbara': 'સગબારા',
    'Nandod': 'નાંદોદ',
    'Rajpipla': 'રાજપીપળા',
    'Chotila': 'છોટીલા',
    'Limbdi': 'લીંબડી',
    'Halvad': 'હળવદ',
    'Dhrangadhra': 'ધ્રાંગધ્રા',
    'Dasada': 'દસાડા',
    'Lakhtar': 'લખતર',
    'Muli': 'મુળી',
    'Sayla': 'સાયલા',
    'Wadhwan': 'વઢવાણ',
    'Thangadh': 'થાનગઢ',
  }
};

export const CITY_KEYS = Object.keys(GUJARAT_CITIES.en);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Home
    'home.title': 'Discover Your Sacred Tree',
    'home.subtitle': 'Based on Vedic astrology, find the trees that resonate with your cosmic energy',
    'home.knowRashi': 'I Know My Rashi',
    'home.knowRashiDesc': 'Select from 12 zodiac signs',
    'home.findRashi': 'Find My Rashi',
    'home.findRashiDesc': 'Calculate using birth details',
    'home.philosophy': 'Even though we firmly believe that "Chod mā Ranchod"— God in every tree—our traditions also hold that, just as certain stones or metals are considered auspicious and beneficial for individuals, Vedic scriptures associate specific trees with different Rashis and recommend planting them to derive their benefits.',
    'home.philosophyDetails': 'Through this tool, you can identify your Rashi and the trees considered auspicious for it, understand their significance, and learn where and how these trees can be planted or obtained, thereby aligning personal well-being with a deeper reverence for nature.',

    // KnowRashi
    'knowRashi.title': 'Select Your Rashi',
    'knowRashi.subtitle': 'Choose your Moon sign (Chandra Rashi) from the 12 zodiac signs below to discover your recommended trees.',

    // Rashi Preview Modal
    'modal.element': 'Element',
    'modal.rulingPlanet': 'Ruling Planet',
    'modal.keyTraits': 'Key Traits',
    'modal.luckyInfo': 'Lucky Day, Color & Number',
    'modal.discoverTrees': 'Discover My Sacred Trees',
    'modal.findingTrees': 'Finding Your Trees...',

    // FindRashi
    'findRashi.title': 'Find Your Rashi',
    'findRashi.subtitle': 'Enter your birth details to calculate your Moon sign',
    'findRashi.name': 'Your Name',
    'findRashi.namePlaceholder': 'Enter your name',
    'findRashi.dob': 'Date of Birth',
    'findRashi.tob': 'Time of Birth',
    'findRashi.tobOptional': '(Optional but recommended)',
    'findRashi.pob': 'Place of Birth',
    'findRashi.pobPlaceholder': 'Type to search city...',
    'findRashi.selectCity': 'Select or search city',
    'findRashi.searching': 'Searching...',
    'findRashi.noResults': 'No locations found',
    'findRashi.calculate': 'Calculate My Rashi',
    'findRashi.calculating': 'Calculating...',
    'findRashi.degrees': 'Degrees',
    'findRashi.minutes': 'Minutes',
    'findRashi.seconds': 'Seconds',
    'findRashi.latitude': 'Latitude',
    'findRashi.longitude': 'Longitude',
    'findRashi.timezone': 'Timezone Offset',

    // Result
    'result.title': 'Your Sacred Trees',
    'result.rashiIs': 'Your Rashi is',
    'result.recommendedTrees': 'Recommended Sacred Trees',
    'result.primaryTree': 'Primary Tree',
    'result.scanQR': 'Scan to save your results',
    'result.startOver': 'Start Over',
    'result.nurseryQR': 'Get Your Trees from Forest Department',
    'result.nurseryInfo': 'Scan this QR code to contact Gujarat Forest Department nursery for obtaining your recommended trees.',

    // Tree Motivation
    'motivation.title': 'Plant a Tree, Nurture Life',
    'motivation.message': 'Trees are the lungs of our Earth. By planting your Rashi tree, you connect with nature and contribute to a greener future for generations to come.',

    // Traits
    'trait.Courageous': 'Courageous',
    'trait.Energetic': 'Energetic',
    'trait.Ambitious': 'Ambitious',
    'trait.Independent': 'Independent',
    'trait.Patient': 'Patient',
    'trait.Reliable': 'Reliable',
    'trait.Devoted': 'Devoted',
    'trait.Practical': 'Practical',
    'trait.Curious': 'Curious',
    'trait.Adaptable': 'Adaptable',
    'trait.Clever': 'Clever',
    'trait.Expressive': 'Expressive',
    'trait.Intuitive': 'Intuitive',
    'trait.Nurturing': 'Nurturing',
    'trait.Protective': 'Protective',
    'trait.Emotional': 'Emotional',
    'trait.Creative': 'Creative',
    'trait.Generous': 'Generous',
    'trait.Confident': 'Confident',
    'trait.Leader': 'Leader',
    'trait.Analytical': 'Analytical',
    'trait.Modest': 'Modest',
    'trait.Diligent': 'Diligent',
    'trait.Perfectionist': 'Perfectionist',
    'trait.Harmonious': 'Harmonious',
    'trait.Fair': 'Fair',
    'trait.Diplomatic': 'Diplomatic',
    'trait.Artistic': 'Artistic',
    'trait.Passionate': 'Passionate',
    'trait.Determined': 'Determined',
    'trait.Magnetic': 'Magnetic',
    'trait.Optimistic': 'Optimistic',
    'trait.Adventurous': 'Adventurous',
    'trait.Philosophical': 'Philosophical',
    'trait.Honest': 'Honest',
    'trait.Disciplined': 'Disciplined',
    'trait.Responsible': 'Responsible',
    'trait.Progressive': 'Progressive',
    'trait.Humanitarian': 'Humanitarian',
    'trait.Original': 'Original',
    'trait.Compassionate': 'Compassionate',
    'trait.Spiritual': 'Spiritual',

    // Timer
    'timer.inactive': 'Session expires in',
  },
  hi: {
    // Home
    'home.title': 'अपना पवित्र वृक्ष खोजें',
    'home.subtitle': 'वैदिक ज्योतिष के आधार पर, अपनी ब्रह्मांडीय ऊर्जा से मेल खाने वाले वृक्ष खोजें',
    'home.knowRashi': 'मुझे मेरी राशि पता है',
    'home.knowRashiDesc': '12 राशियों में से चुनें',
    'home.findRashi': 'मेरी राशि खोजें',
    'home.findRashiDesc': 'जन्म विवरण से गणना करें',
    'home.philosophy': 'हालांकि हम दृढ़ता से मानते हैं कि "छोड़ मां रणछोड़"— हर पेड़ में ईश्वर है—हमारी परंपराएं यह भी मानती हैं कि जिस प्रकार कुछ पत्थर या धातुएं शुभ और लाभकारी मानी जाती हैं, उसी प्रकार वैदिक ग्रंथ विशिष्ट वृक्षों को विभिन्न राशियों से जोड़ते हैं और उनके लाभ प्राप्त करने के लिए उन्हें लगाने की सलाह देते हैं।',
    'home.philosophyDetails': 'इस टूल के माध्यम से, आप अपनी राशि और उससे संबंधित शुभ वृक्षों की पहचान कर सकते हैं, उनके महत्व को समझ सकते हैं और यह जान सकते हैं कि इन वृक्षों को कहां और कैसे लगाया या प्राप्त किया जा सकता है, जिससे आपका व्यक्तिगत कल्याण प्रकृति के प्रति गहरी श्रद्धा से जुड़ जाएगा।',

    // KnowRashi
    'knowRashi.title': 'अपनी राशि चुनें',
    'knowRashi.subtitle': 'अपने अनुशंसित वृक्षों को जानने के लिए नीचे दी गई 12 राशियों में से अपनी चंद्र राशि चुनें।',

    // Rashi Preview Modal
    'modal.element': 'तत्व',
    'modal.rulingPlanet': 'स्वामी ग्रह',
    'modal.keyTraits': 'मुख्य विशेषताएं',
    'modal.luckyInfo': 'शुभ दिन, रंग और अंक',
    'modal.discoverTrees': 'मेरे पवित्र वृक्ष खोजें',
    'modal.findingTrees': 'आपके वृक्ष खोज रहे हैं...',

    // FindRashi
    'findRashi.title': 'अपनी राशि खोजें',
    'findRashi.subtitle': 'अपनी चंद्र राशि की गणना के लिए जन्म विवरण दर्ज करें',
    'findRashi.name': 'आपका नाम',
    'findRashi.namePlaceholder': 'अपना नाम दर्ज करें',
    'findRashi.dob': 'जन्म तिथि',
    'findRashi.tob': 'जन्म समय',
    'findRashi.tobOptional': '(वैकल्पिक लेकिन अनुशंसित)',
    'findRashi.pob': 'जन्म स्थान',
    'findRashi.pobPlaceholder': 'शहर खोजने के लिए टाइप करें...',
    'findRashi.selectCity': 'शहर चुनें या खोजें',
    'findRashi.searching': 'खोज रहे हैं...',
    'findRashi.noResults': 'कोई स्थान नहीं मिला',
    'findRashi.calculate': 'मेरी राशि गणना करें',
    'findRashi.calculating': 'गणना हो रही है...',
    'findRashi.degrees': 'डिग्री',
    'findRashi.minutes': 'मिनट',
    'findRashi.seconds': 'सेकंड',
    'findRashi.latitude': 'अक्षांश',
    'findRashi.longitude': 'देशांतर',
    'findRashi.timezone': 'समय क्षेत्र ऑफसेट',

    // Result
    'result.title': 'आपके पवित्र वृक्ष',
    'result.rashiIs': 'आपकी राशि है',
    'result.recommendedTrees': 'अनुशंसित पवित्र वृक्ष',
    'result.primaryTree': 'मुख्य वृक्ष',
    'result.scanQR': 'अपने परिणाम सहेजने के लिए स्कैन करें',
    'result.startOver': 'फिर से शुरू करें',
    'result.nurseryQR': 'वन विभाग से अपने वृक्ष प्राप्त करें',
    'result.nurseryInfo': 'अपने अनुशंसित वृक्ष प्राप्त करने के लिए गुजरात वन विभाग नर्सरी से संपर्क करने हेतु इस QR कोड को स्कैन करें।',

    // Tree Motivation
    'motivation.title': 'वृक्ष लगाओ, जीवन पालो',
    'motivation.message': 'वृक्ष हमारी पृथ्वी के फेफड़े हैं। अपना राशि वृक्ष लगाकर, आप प्रकृति से जुड़ते हैं और आने वाली पीढ़ियों के लिए हरित भविष्य में योगदान करते हैं।',

    // Traits
    'trait.Courageous': 'साहसी',
    'trait.Energetic': 'ऊर्जावान',
    'trait.Ambitious': 'महत्वाकांक्षी',
    'trait.Independent': 'स्वतंत्र',
    'trait.Patient': 'धैर्यवान',
    'trait.Reliable': 'विश्वसनीय',
    'trait.Devoted': 'समर्पित',
    'trait.Practical': 'व्यावहारिक',
    'trait.Curious': 'जिज्ञासु',
    'trait.Adaptable': 'अनुकूलनीय',
    'trait.Clever': 'चतुर',
    'trait.Expressive': 'अभिव्यक्त',
    'trait.Intuitive': 'सहज ज्ञानी',
    'trait.Nurturing': 'पोषण करने वाला',
    'trait.Protective': 'रक्षात्मक',
    'trait.Emotional': 'भावुक',
    'trait.Creative': 'रचनात्मक',
    'trait.Generous': 'उदार',
    'trait.Confident': 'आत्मविश्वासी',
    'trait.Leader': 'नेता',
    'trait.Analytical': 'विश्लेषणात्मक',
    'trait.Modest': 'विनम्र',
    'trait.Diligent': 'परिश्रमी',
    'trait.Perfectionist': 'पूर्णतावादी',
    'trait.Harmonious': 'सामंजस्यपूर्ण',
    'trait.Fair': 'निष्पक्ष',
    'trait.Diplomatic': 'कूटनीतिक',
    'trait.Artistic': 'कलात्मक',
    'trait.Passionate': 'जोशीला',
    'trait.Determined': 'दृढ़ निश्चयी',
    'trait.Magnetic': 'आकर्षक',
    'trait.Optimistic': 'आशावादी',
    'trait.Adventurous': 'साहसिक',
    'trait.Philosophical': 'दार्शनिक',
    'trait.Honest': 'ईमानदार',
    'trait.Disciplined': 'अनुशासित',
    'trait.Responsible': 'जिम्मेदार',
    'trait.Progressive': 'प्रगतिशील',
    'trait.Humanitarian': 'मानवतावादी',
    'trait.Original': 'मौलिक',
    'trait.Compassionate': 'करुणामय',
    'trait.Spiritual': 'आध्यात्मिक',

    // Timer
    'timer.inactive': 'सत्र समाप्त होगा',
  },
  gu: {
    // Home
    'home.title': 'તમારું પવિત્ર વૃક્ષ શોધો',
    'home.subtitle': 'વૈદિક જ્યોતિષ પર આધારિત, તમારી બ્રહ્માંડીય ઊર્જા સાથે મેળ ખાતા વૃક્ષો શોધો',
    'home.knowRashi': 'મને મારી રાશિ ખબર છે',
    'home.knowRashiDesc': '12 રાશિઓમાંથી પસંદ કરો',
    'home.findRashi': 'મારી રાશિ શોધો',
    'home.findRashiDesc': 'જન્મ વિગતોથી ગણતરી કરો',
    'home.philosophy': 'ભલે આપણે દ્રઢપણે માનીએ છીએ કે "છોડ મા રણછોડ" - દરેક વૃક્ષમાં ભગવાન - આપણી પરંપરાઓ પણ એવું માને છે કે, જેમ અમુક પથ્થરો અથવા ધાતુઓને વ્યક્તિઓ માટે શુભ અને લાભદાયી માનવામાં આવે છે, તેમ વૈદિક શાસ્ત્રો ચોક્કસ વૃક્ષોને વિવિધ રાશિઓ સાથે સાંકળે છે અને તેમના લાભ મેળવવા માટે તેમને રોપવાની ભલામણ કરે છે.',
    'home.philosophyDetails': 'આ સાધન દ્વારા, તમે તમારી રાશિ અને તેના માટે શુભ માનવામાં આવતા વૃક્ષોને ઓળખી શકો છો, તેમનું મહત્વ સમજી શકો છો અને આ વૃક્ષો ક્યાં અને કેવી રીતે વાવી શકાય અથવા મેળવી શકાય તે શીખી શકો છો, જેનાથી વ્યક્તિગત સુખાકારી પ્રકૃતિ પ્રત્યેના ઊંડા આદર સાથે સુસંગત બને છે.',

    // KnowRashi
    'knowRashi.title': 'તમારી રાશિ પસંદ કરો',
    'knowRashi.subtitle': 'તમારા ભલામણ કરેલા વૃક્ષો જાણવા માટે નીચેની 12 રાશિઓમાંથી તમારી ચંદ્ર રાશિ પસંદ કરો.',

    // Rashi Preview Modal
    'modal.element': 'તત્વ',
    'modal.rulingPlanet': 'સ્વામી ગ્રહ',
    'modal.keyTraits': 'મુખ્ય લક્ષણો',
    'modal.luckyInfo': 'શુભ દિવસ, રંગ અને અંક',
    'modal.discoverTrees': 'મારા પવિત્ર વૃક્ષો શોધો',
    'modal.findingTrees': 'તમારા વૃક્ષો શોધી રહ્યા છે...',

    // FindRashi
    'findRashi.title': 'તમારી રાશિ શોધો',
    'findRashi.subtitle': 'તમારી ચંદ્ર રાશિની ગણતરી માટે જન્મ વિગતો દાખલ કરો',
    'findRashi.name': 'તમારું નામ',
    'findRashi.namePlaceholder': 'તમારું નામ દાખલ કરો',
    'findRashi.dob': 'જન્મ તારીખ',
    'findRashi.tob': 'જન્મ સમય',
    'findRashi.tobOptional': '(વૈકલ્પિક પણ ભલામણ કરેલ)',
    'findRashi.pob': 'જન્મ સ્થળ',
    'findRashi.pobPlaceholder': 'શહેર શોધવા ટાઈપ કરો...',
    'findRashi.selectCity': 'શહેર પસંદ કરો અથવા શોધો',
    'findRashi.searching': 'શોધી રહ્યા છે...',
    'findRashi.noResults': 'કોઈ સ્થળ મળ્યું નથી',
    'findRashi.calculate': 'મારી રાશિ ગણતરી કરો',
    'findRashi.calculating': 'ગણતરી થઈ રહી છે...',
    'findRashi.degrees': 'ડિગ્રી',
    'findRashi.minutes': 'મિનિટ',
    'findRashi.seconds': 'સેકન્ડ',
    'findRashi.latitude': 'અક્ષાંશ',
    'findRashi.longitude': 'રેખાંશ',
    'findRashi.timezone': 'સમય ક્ષેત્ર ઓફસેટ',

    // Result
    'result.title': 'તમારા પવિત્ર વૃક્ષો',
    'result.rashiIs': 'તમારી રાશિ છે',
    'result.recommendedTrees': 'ભલામણ કરેલ પવિત્ર વૃક્ષો',
    'result.primaryTree': 'મુખ્ય વૃક્ષ',
    'result.scanQR': 'તમારા પરિણામો સાચવવા સ્કેન કરો',
    'result.startOver': 'ફરીથી શરૂ કરો',
    'result.nurseryQR': 'વન વિભાગમાંથી તમારા વૃક્ષો મેળવો',
    'result.nurseryInfo': 'તમારા ભલામણ કરેલા વૃક્ષો મેળવવા માટે ગુજરાત વન વિભાગ નર્સરીનો સંપર્ક કરવા આ QR કોડ સ્કેન કરો.',

    // Tree Motivation
    'motivation.title': 'વૃક્ષ વાવો, જીવન ઉછેરો',
    'motivation.message': 'વૃક્ષો આપણી પૃથ્વીના ફેફસાં છે. તમારું રાશિ વૃક્ષ વાવીને, તમે પ્રકૃતિ સાથે જોડાઓ છો અને આવનારી પેઢીઓ માટે હરિયાળા ભવિષ્યમાં યોગદાન આપો છો.',

    // Traits
    'trait.Courageous': 'હિંમતવાન',
    'trait.Energetic': 'ઊર્જાવાન',
    'trait.Ambitious': 'મહત્વાકાંક્ષી',
    'trait.Independent': 'સ્વતંત્ર',
    'trait.Patient': 'ધીરજવાન',
    'trait.Reliable': 'વિશ્વસનીય',
    'trait.Devoted': 'સમર્પિત',
    'trait.Practical': 'વ્યવહારુ',
    'trait.Curious': 'જિજ્ઞાસુ',
    'trait.Adaptable': 'અનુકૂલનશીલ',
    'trait.Clever': 'ચતુર',
    'trait.Expressive': 'અભિવ્યક્ત',
    'trait.Intuitive': 'સહજ જ્ઞાની',
    'trait.Nurturing': 'પોષણ કરનાર',
    'trait.Protective': 'રક્ષણાત્મક',
    'trait.Emotional': 'ભાવુક',
    'trait.Creative': 'સર્જનાત્મક',
    'trait.Generous': 'ઉદાર',
    'trait.Confident': 'આત્મવિશ્વાસી',
    'trait.Leader': 'નેતા',
    'trait.Analytical': 'વિશ્લેષણાત્મક',
    'trait.Modest': 'વિનમ્ર',
    'trait.Diligent': 'મહેનતુ',
    'trait.Perfectionist': 'પૂર્ણતાવાદી',
    'trait.Harmonious': 'સુમેળભર્યા',
    'trait.Fair': 'ન્યાયી',
    'trait.Diplomatic': 'કૂટનીતિક',
    'trait.Artistic': 'કલાત્મક',
    'trait.Passionate': 'જોશીલા',
    'trait.Determined': 'દ્રઢ નિશ્ચયી',
    'trait.Magnetic': 'આકર્ષક',
    'trait.Optimistic': 'આશાવાદી',
    'trait.Adventurous': 'સાહસિક',
    'trait.Philosophical': 'દાર્શનિક',
    'trait.Honest': 'પ્રામાણિક',
    'trait.Disciplined': 'શિસ્તબદ્ધ',
    'trait.Responsible': 'જવાબદાર',
    'trait.Progressive': 'પ્રગતિશીલ',
    'trait.Humanitarian': 'માનવતાવાદી',
    'trait.Original': 'મૌલિક',
    'trait.Compassionate': 'કરુણાશીલ',
    'trait.Spiritual': 'આધ્યાત્મિક',

    // Timer
    'timer.inactive': 'સત્ર સમાપ્ત થશે',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
